### ISSUE TITLE
Support SASL authentication

### ISSUE THREAD

**Issue by hlwanghl** [QingCloudAppcenter/Kafka#9]
- [ ] [SASL/PLAIN](https://docs.confluent.io/current/kafka/authentication_sasl/authentication_sasl_plain.html)
- [ ] [SASL/GSSAPI](https://docs.confluent.io/current/kafka/authentication_sasl/authentication_sasl_gssapi.html)

ref: https://docs.confluent.io/3.0.0/kafka/sasl.html

**Comment by spwangxp** [comment]
sasl/plain:  需要在启动之初就配置好用户名密码，后续无法新增用户，可以[改写callback来增加动态支持](https://cwiki.apache.org/confluence/display/KAFKA/KIP-86%3A+Configurable+SASL+callback+handlers#KIP86:ConfigurableSASLcallbackhandlers-SASL/SCRAMServerCallbacks)，但需要Java。此方式无需改造 zookeeper。
sasl/scram: 可以动态增加用户修改密码，但需要改造 zookeeper 配置文件。部分第三方包不支持

ref: 
https://stackoverflow.com/questions/43469962/kafka-sasl-zookeeper-authentication
https://www.cnblogs.com/listenfwind/p/14026462.html

**Comment by spwangxp** [comment]
ssl: 较复杂，客户端需要配置证书

ref: 
https://docs.confluent.io/4.0.0/kafka/encryption.html
https://medium.com/analytics-vidhya/kafka-ssl-encryption-authentication-part-two-practical-example-for-implementing-ssl-in-kafka-d514f30fe782
https://stackoverflow.com/questions/52590351/apache-kafka-2-0-0-version-connection-to-node-1-failed-authentication-due-to/52596180
